name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:   # <— enables “Run workflow” button

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - run: python -m pip install -U pip
      - run: python -m pip install -e ".[test]"
      - run: pytest -q

      - name: Exercise CLI (csv2json)
        shell: bash
        run: | 
          # Fallback to module form if console script isn't on PATH
          if ! command -v csv2json >/dev/null 2>&1; then
            csv2json() { python -m csvtojson.cli "$@"; }
          fi

          # 1) Create a tiny CSV
          printf "name,age,active\nAlice,30,true\nBob,5,false\n" > sample.csv

          cat sample.csv

          # 2) Run CLI (prints output path)
          OUT=$(csv2json sample.csv)
          echo "CLI wrote: $OUT"
          test -f "$OUT"

          cat sample.json

          # 3) Validate JSON content
          python - <<'PY' "$OUT"
          import json, sys, pathlib
          p = pathlib.Path(sys.argv[1])
          data = json.loads(p.read_text(encoding="utf-8"))
          assert data == [
              {"name": "Alice", "age": 30, "active": True},
              {"name": "Bob", "age": 5, "active": False},
          ], data
          print("OK: CLI JSON content matches expected")
          PY

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov-${{ matrix.python-version }}
          path: htmlcov/
          if-no-files-found: ignore

      - name: Publish coverage to job summary
        run: |
          python - <<'PY'
          import os, xml.etree.ElementTree as ET
          root = ET.parse("coverage.xml").getroot()  # Cobertura XML
          lr  = float(root.attrib.get("line-rate", 0.0))
          br  = float(root.attrib.get("branch-rate", 0.0))
          lv  = int(root.attrib.get("lines-valid", 0))
          lc  = int(root.attrib.get("lines-covered", 0))
          md  = []
          md.append("# Coverage Summary")
          md.append(f"**Line:** {lr*100:.2f}% ({lc}/{lv})")
          if "branch-rate" in root.attrib:
              md.append(f"**Branch:** {br*100:.2f}%")
          # Lowest-covered files table (top 10)
          files = []
          for cls in root.iter("class"):
              fn = cls.attrib["filename"]
              lines = [int(l.attrib["hits"]>0) for l in cls.iter("line")]
              valid = len(lines)
              covered = sum(lines)
              rate = 100.0 if valid==0 else covered/valid*100
              files.append((rate, covered, valid, fn))
          files.sort(key=lambda x: x[0])
          table = ["\n## Lowest-covered files",
                   "\n| File | Coverage | Covered/Valid |",
                   "|---|---:|---:|"]
          for rate, cov, valid, fn in files[:10]:
              table.append(f"| `{fn}` | {rate:.1f}% | {cov}/{valid} |")
          out = "\n\n".join(md + ["\n".join(table)])
          with open(os.environ["GITHUB_STEP_SUMMARY"], "a", encoding="utf-8") as f:
              f.write(out + "\n")
          PY